run:
    capsule: predicting-disease-genes
    data: s3a://sagemaker-eu-west-1-366243680492/spark-example/netflix_titles.csv
    results: s3a://sagemaker-eu-west-1-366243680492/spark-example/netflix_titles.parquet
    instance_type: ml.m5.xlarge
